name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22.13.1
      - run: npm ci
      - run: npm run build
      - name: Deploy to Firebase Hosting (Live)
        uses: FirebaseExtended/action-hosting-deploy@v1
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGENDA_DEL_RUNNER_TEST }}
          projectId: agenda-del-runner-test
          target: live
